export const PRICING_PLANS = [
  {
    id: 'basic',
    name: 'BASIC',
    priceRange: '₹5k – 8k',
    color: '#3b4fa8',
    glowColor: 'rgba(59, 79, 168, 0.3)',
    borderColor: 'rgba(59, 79, 168, 0.5)',
    popular: false,
    features: [
      'Basic Theme Design',
      'Responsive Design',
      '1 – 3 Pages',
      '1 Revision',
      'Contact Form',
      'Static Website',
      '3 Days Delivery',
      'Frontend Only Website',
      'No Database',
    ],
    idealFor: ['Local Shops', 'Portfolio Websites', 'Personal Brand', 'Small Businesses'],
  },
  {
    id: 'pro',
    name: 'PRO',
    priceRange: '₹10k – 15k',
    color: '#1a6b3a',
    glowColor: 'rgba(26, 107, 58, 0.3)',
    borderColor: 'rgba(26, 107, 58, 0.5)',
    popular: true,
    features: [
      'Modern Theme Design',
      'Responsive Animations',
      '5 – 8 Pages',
      'Basic Backend (Node.js)',
      'Data Integration',
      'Basic SEO Setup',
      '2 – 3 Revisions',
      '15 Days Delivery',
      'Login / Signup System',
      '15 Days Maintenance & Support',
    ],
    idealFor: ['Coaching Centers', 'Startups', 'Business Websites', 'Service Platforms'],
  },
  {
    id: 'premium',
    name: 'PREMIUM',
    priceRange: '₹18k – 20k+',
    color: '#6b3fa8',
    glowColor: 'rgba(107, 63, 168, 0.3)',
    borderColor: 'rgba(107, 63, 168, 0.5)',
    popular: false,
    features: [
      'Advanced UI / UX',
      '10 – 15 Pages',
      'Full Backend',
      'Authentication & Authorization',
      'Payment Gateway',
      'Advanced SEO',
      '5 – 10 Revisions',
      '3 – 4 Weeks Delivery',
      '30 Days Maintenance & Support',
    ],
    idealFor: ['E-commerce Platforms', 'SaaS Applications', 'Large Business Websites', 'Full Web Applications'],
  },
];

export const PRICING_NOTES = [
  {
    title: 'Extra Charges',
    icon: '🏷',
    items: ['Domain : Extra', 'Hosting : Extra', 'Content Writing : Extra', 'Logo Design : Extra'],
  },
  {
    title: 'Payment Terms',
    icon: '💳',
    items: ['50% Advance', '50% After Completion', 'Project starts after advance payment'],
  },
  {
    title: 'Revision Policy',
    icon: '🔄',
    items: ['Revisions include minor changes only', 'Major redesign or additional features will be chargeable'],
  },
  {
    title: 'Note',
    icon: '📋',
    items: ['Prices may vary depending on project complexity and specific requirements'],
  },
];