export const SERVICES = [
  {
    id: 1,
    icon: '⬡',
    title: 'Web Development',
    description: 'Full-stack modern websites built with cutting-edge technologies. Fast, secure, and scalable from the ground up.',
    tags: ['React', 'Node.js', 'MongoDB'],
    color: '#00c8ff',
  },
  {
    id: 2,
    icon: '◈',
    title: 'Landing Page Dev',
    description: 'High-converting landing pages with premium UI, cinematic animations, and laser-focused CTAs that drive results.',
    tags: ['GSAP', 'Tailwind', 'Vite'],
    color: '#7b5ea7',
  },
  {
    id: 3,
    icon: '◎',
    title: 'MERN Stack Apps',
    description: 'End-to-end full-stack applications — MongoDB, Express, React, Node.js — architected for real-world scale.',
    tags: ['MongoDB', 'Express', 'React'],
    color: '#00ffa3',
  },
  {
    id: 4,
    icon: '⬙',
    title: 'UI/UX Design',
    description: 'Pixel-perfect interfaces designed with intent. Every detail crafted for user delight and conversion.',
    tags: ['Figma', 'Prototyping', 'Research'],
    color: '#ff6b6b',
  },
  {
    id: 5,
    icon: '◇',
    title: 'Portfolio Websites',
    description: 'Bespoke personal portfolios that make a statement. Designed to land you opportunities.',
    tags: ['React', 'GSAP', 'Custom'],
    color: '#ffd700',
  },
  {
    id: 6,
    icon: '⬟',
    title: 'Website Optimization',
    description: 'Speed, SEO, and Core Web Vitals — we audit and optimize your existing site for peak performance.',
    tags: ['Performance', 'SEO', 'Lighthouse'],
    color: '#00c8ff',
  },
  {
    id: 7,
    icon: '⬠',
    title: 'Custom Web Solutions',
    description: 'Have a unique idea? We architect and build bespoke web solutions tailored to your exact requirements.',
    tags: ['Custom', 'Consulting', 'Architecture'],
    color: '#7b5ea7',
  },
];